# Generated by Django 5.1.4 on 2024-12-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='biography',
            field=models.TextField(null=True, verbose_name='Биография'),
        ),
    ]
