# Generated by Django 5.1.4 on 2024-12-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_authors_slug_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='biography',
            field=models.TextField(default='some information', verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
    ]
