# Generated by Django 5.1.4 on 2024-12-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
