# Generated by Django 5.1.4 on 2025-01-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_alter_authors_slug_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Меню')),
                ('url_name', models.CharField(max_length=100, verbose_name='Эндпоинт')),
            ],
        ),
    ]
