# Generated by Django 5.1.4 on 2025-01-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото автора'),
        ),
    ]
