# Generated by Django 5.1.4 on 2025-01-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_quotes_status_alter_authors_name_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='category',
            field=models.ManyToManyField(related_name='category', to='quotes.category', verbose_name='quotes'),
        ),
    ]
