# Generated by Django 5.1.5 on 2025-01-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_alter_quotes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='quote',
            field=models.TextField(db_index=True, verbose_name='Цитата'),
        ),
    ]
