# Generated by Django 5.1.5 on 2025-02-10 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_alter_quotes_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_quotes', to='quotes.authors', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='category',
            field=models.ManyToManyField(related_name='category_quotes', to='quotes.category', verbose_name='Категории'),
        ),
    ]
